---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
       update_cache: yes
           
  - name: installing apache2 package
    apt:
      name: apache2

  - name: add php support for apache
    apt:
      name: libapache2-mod-php

